server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    host: localhost # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: guest
    password: guest

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall

mybatis:
  mapper-locations:
    - classpath:sql/*.xml

redis:
  database: mall
  key:
    member: 'member'
    admin: 'admin'
    cart: 'cart'
  expire:
    common: 2592000 # 默认30d超时
